name: Build

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "src/Sonarr.Api.*/openapi.json"
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - "src/NzbDrone.Core/Localization/Core/**"
      - "src/Sonarr.Api.*/openapi.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FRAMEWORK: net6.0
  RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  SONARR_MAJOR_VERSION: 4
  VERSION: 4.0.19

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      framework: ${{ steps.variables.outputs.framework }}
      major_version: ${{ steps.variables.outputs.major_version }}
      version: ${{ steps.variables.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Setup Environment Variables
        id: variables
        shell: bash
        run: |
          SONARR_VERSION="${{ env.VERSION }}.$((${{ github.run_number }}+800))"
          DOTNET_VERSION=$(jq -r '.sdk.version' global.json)

          echo "SDK_PATH=${{ env.DOTNET_ROOT }}/sdk/${DOTNET_VERSION}" >> "$GITHUB_ENV"
          echo "SONARR_VERSION=$SONARR_VERSION" >> "$GITHUB_ENV"
          echo "BRANCH=${RAW_BRANCH_NAME//\//-}" >> "$GITHUB_ENV"

          echo "framework=${{ env.FRAMEWORK }}" >> "$GITHUB_OUTPUT"
          echo "major_version=${{ env.SONARR_MAJOR_VERSION }}" >> "$GITHUB_OUTPUT"
          echo "version=$SONARR_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Backend & Frontend
        shell: bash
        run: ./build.sh --backend --frontend --packages -f net6.0 -r linux-x64

      - name: Publish linux-x64 Test Artifact
        uses: ./.github/actions/publish-test-artifact
        with:
          framework: ${{ env.FRAMEWORK }}
          runtime: linux-x64

      - name: Publish Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_linux
          path: _artifacts

  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test
        with:
          os: ubuntu-latest
          artifact: tests-linux-x64
          pattern: Sonarr.*.Test.dll
          filter: TestCategory!=ManualTest&TestCategory!=WINDOWS&TestCategory!=IntegrationTest&TestCategory!=AutomationTest

  unit_test_postgres:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test
        with:
          os: ubuntu-latest
          artifact: tests-linux-x64
          pattern: Sonarr.*.Test.dll
          filter: TestCategory!=ManualTest&TestCategory!=WINDOWS&TestCategory!=IntegrationTest&TestCategory!=AutomationTest
          use_postgres: true

  integration_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test
        with:
          os: ubuntu-latest
          artifact: tests-linux-x64
          pattern: Sonarr.*.Test.dll
          filter: TestCategory!=ManualTest&TestCategory!=WINDOWS&TestCategory=IntegrationTest
          integration_tests: true
          binary_artifact: build_linux
          binary_path: linux-x64/${{ needs.build.outputs.framework }}/Sonarr
